<script setup lang="ts">
import { Award, ExternalLink, Heart, Mail, MessageCircle, TrendingUp } from 'lucide-vue-next'
import { computed, onMounted, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { getApiErrorMessage } from '@/api/http'
import { useSiteStore } from '@/stores/site'

const store = useSiteStore()
const { basicInfo, matrixAccounts } = storeToRefs(store)
const errorMessage = ref('')
const formatCount = (count: number) => count >= 10_000 ? `${Math.floor(count / 10_000)}万+` : `${count}`
const stats = computed(() => [{ label: '全网播放量', value: formatCount(basicInfo.value?.totalPlayCount ?? 0), icon: TrendingUp }, { label: '全网点赞数', value: formatCount(basicInfo.value?.totalLikeCount ?? 0), icon: Heart }, { label: '全网粉丝数', value: formatCount(basicInfo.value?.totalFollowerCount ?? 0), icon: Award }])
const milestones = [{ year: 2020, title: '开始剪辑创作', description: '第一条爆款视频播放破100万，正式踏上创作之路' }, { year: 2022, title: '粉丝突破10万', description: '成为抖音独家创作者，获得平台流量扶持' }, { year: 2024, title: '入选精选计划', description: '入选抖音精选创作者计划，单条作品播放破500万' }, { year: 2026, title: '全网24万粉丝', description: '全网粉丝突破24万，开启商业化运营新阶段' }]
onMounted(async () => {
  try { await Promise.all([store.loadBasicInfo(), store.loadMatrixAccounts()]) }
  catch (error) { errorMessage.value = getApiErrorMessage(error, '关于页面内容加载失败') }
})
</script>
<template><div class="min-h-screen bg-gradient-to-b from-gray-50 to-white"><div v-if="errorMessage" class="bg-red-50 px-4 py-4 text-center text-red-700">{{ errorMessage }}</div><section class="bg-gradient-to-r from-blue-600 to-purple-600 px-4 py-20 text-white"><div class="mx-auto grid max-w-7xl grid-cols-1 items-center gap-12 md:grid-cols-2"><div><h1 class="mb-4 text-5xl font-bold">关于我</h1><div class="space-y-4 text-lg text-blue-100"><p class="text-2xl font-medium text-white">{{ basicInfo?.authorIdentityTag || '影像创作者' }}</p><p v-if="basicInfo?.slogan" class="border-l-4 border-white/50 pl-4 text-xl italic">“{{ basicInfo.slogan }}”</p><p>{{ basicInfo?.creationAttitude }}</p></div><div class="mt-8 flex flex-wrap gap-3"><a v-for="account in matrixAccounts" :key="account.id" :href="account.accountUrl || undefined" target="_blank" rel="noopener noreferrer" :class="[account.colorClass, 'flex items-center gap-2 rounded-full px-4 py-2 text-sm text-white']">{{ account.platformName }}<span class="text-xs opacity-80">{{ account.followerCountText }}</span></a></div></div><div class="flex justify-center"><div class="relative"><div class="h-80 w-80 overflow-hidden rounded-2xl bg-white/10 shadow-2xl"><img v-if="basicInfo?.authorPhoto" :src="basicInfo.authorPhoto" alt="创作者照片" class="h-full w-full object-cover" /></div><div class="absolute -bottom-4 -right-4 rounded-xl bg-white px-6 py-3 text-gray-900 shadow-lg"><div class="text-sm text-gray-600">电影解说创作者</div><div class="text-lg font-bold">@影像创作者</div></div></div></div></div></section>
<section class="bg-white px-4 py-12"><div class="mx-auto grid max-w-5xl grid-cols-1 gap-8 md:grid-cols-3"><div v-for="stat in stats" :key="stat.label" class="text-center"><component :is="stat.icon" class="mx-auto mb-3 h-8 w-8 text-blue-600" /><div class="mb-2 text-4xl font-bold">{{ stat.value }}</div><div class="text-gray-600">{{ stat.label }}</div></div></div></section>
<section class="bg-gray-50 px-4 py-20"><div class="mx-auto max-w-5xl"><div class="mb-12 text-center"><h2 class="mb-4 text-4xl font-bold">成长里程碑</h2><p class="text-gray-600">记录每一个重要时刻</p></div><div class="relative space-y-12 before:absolute before:left-1/2 before:hidden before:h-full before:w-0.5 before:bg-blue-200 md:before:block"><div v-for="(milestone, index) in milestones" :key="milestone.year" class="relative flex" :class="index % 2 ? 'md:flex-row-reverse' : ''"><div class="w-full md:w-5/12" :class="index % 2 ? 'md:pl-8' : 'md:pr-8 md:text-right'"><div class="rounded-xl bg-white p-6 shadow-lg"><div class="mb-2 text-2xl font-bold text-blue-600">{{ milestone.year }}</div><h3 class="mb-2 text-xl font-semibold">{{ milestone.title }}</h3><p class="text-gray-600">{{ milestone.description }}</p></div></div><div class="absolute left-1/2 hidden h-4 w-4 -translate-x-1/2 rounded-full border-4 border-white bg-blue-600 shadow-lg md:block" /></div></div></div></section>
<section class="bg-white px-4 py-20"><div class="mx-auto max-w-7xl"><div class="mb-12 text-center"><h2 class="mb-4 text-4xl font-bold">幕后故事</h2><p class="text-gray-600">记录创作的每一个瞬间</p></div><div class="mb-12 grid grid-cols-1 gap-8 md:grid-cols-3"><div v-for="item in [{src:basicInfo?.editingDeskWorkPhoto,text:'剪辑台工作日常'},{src:basicInfo?.assetLibraryScreenshot,text:'素材库整理记录'},{src:basicInfo?.dailyMovieWatchingPhoto,text:'观影学习时刻'}]" :key="item.text" class="overflow-hidden rounded-xl shadow-lg"><img v-if="item.src" :src="item.src" :alt="item.text" class="h-64 w-full object-cover" /><div v-else class="h-64 bg-gray-100" /><div class="bg-gray-50 p-4 text-sm text-gray-600">{{ item.text }}</div></div></div><div class="grid grid-cols-1 gap-8 md:grid-cols-2"><div class="rounded-2xl bg-gradient-to-br from-blue-50 to-purple-50 p-8"><h3 class="mb-4 text-2xl font-bold">我的年度十佳影片</h3><p class="mb-4 text-sm text-gray-600">这些电影深刻影响了我的剪辑理念</p><ul class="space-y-2"><li v-for="(film,index) in basicInfo?.annualTop10Films || []" :key="film" class="flex gap-2"><span class="font-bold text-blue-600">{{ index + 1 }}.</span>{{ film }}</li></ul></div><div class="rounded-2xl bg-gradient-to-br from-purple-50 to-pink-50 p-8"><h3 class="mb-4 text-2xl font-bold">影响我的三位导演</h3><p class="mb-4 text-sm text-gray-600">向大师学习，不断精进</p><div class="space-y-4"><div v-for="(director,index) in basicInfo?.influentialThreeDirectors || []" :key="director" class="flex items-center gap-3 rounded-lg bg-white p-4"><span class="flex h-8 w-8 items-center justify-center rounded-full bg-purple-600 font-bold text-white">{{ index + 1 }}</span>{{ director }}</div></div></div></div></div></section>
<section class="bg-gradient-to-r from-blue-600 to-purple-600 px-4 py-20 text-white"><div class="mx-auto max-w-4xl text-center"><h2 class="mb-4 text-4xl font-bold">联系方式</h2><p class="mb-12 text-xl text-blue-100">期待与您的合作</p><div class="grid grid-cols-1 gap-8 md:grid-cols-2"><div class="rounded-2xl bg-white/10 p-8 backdrop-blur-md"><Mail class="mx-auto mb-4 h-12 w-12" /><h3 class="mb-2 text-xl font-semibold">商务合作邮箱</h3><p class="mb-4 text-blue-100">{{ basicInfo?.contactEmail || '暂未配置' }}</p><a v-if="basicInfo?.contactEmail" :href="`mailto:${basicInfo.contactEmail}`" class="inline-flex items-center gap-2 text-sm">发送邮件<ExternalLink class="h-4 w-4" /></a></div><div class="rounded-2xl bg-white/10 p-8 backdrop-blur-md"><MessageCircle class="mx-auto mb-4 h-12 w-12" /><h3 class="mb-2 text-xl font-semibold">合作微信</h3><p class="mb-4 text-blue-100">{{ basicInfo?.contactInfo || '暂未配置' }}</p><img v-if="basicInfo?.contactQrCode" :src="basicInfo.contactQrCode" alt="联系二维码" class="mx-auto h-32 w-32 bg-white object-contain p-2" /></div></div></div></section></div></template>
