server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /uploads/ {
        proxy_pass http://pbw-java-backend:8088;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
